# Generated by Django 6.1.1 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="LPGBrand",
            fields=[
                ("brand_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name_en", models.CharField(max_length=160, verbose_name="English name")),
                ("name_ne", models.CharField(max_length=160, verbose_name="Nepali name")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["brand_id"],
                "verbose_name": "LPG brand",
                "verbose_name_plural": "LPG brands",
            },
        ),
    ]
