# Generated by Django 6.1.1 on 2026-09-11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from applicants.models import current_month_start


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("municipality", models.CharField(max_length=120)),
                ("ward", models.CharField(max_length=20)),
                ("tole", models.CharField(max_length=160, verbose_name="Tole / street")),
                ("house_number", models.CharField(max_length=40)),
                ("flat_unit", models.CharField(blank=True, max_length=40, verbose_name="Flat / unit number")),
                ("family_size", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("members", models.TextField(blank=True, help_text="Optional for the MVP; add household members one per line when needed for verification.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_households", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["municipality", "ward", "tole", "house_number"]},
        ),
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mobile_number", models.CharField(max_length=20, unique=True)),
                ("mobile_verified", models.BooleanField(default=False)),
                ("household", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="applicant_profiles", to="applicants.household")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="applicant_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LPGApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(editable=False, max_length=24, unique=True)),
                ("category", models.CharField(choices=[("labourer", "Labourer"), ("student", "Student"), ("household", "Individual / Family / Household")], max_length=20)),
                ("brand_preference", models.CharField(choices=[("any", "Any available brand"), ("specific", "Prefer a specific brand")], default="any", max_length=20)),
                ("preferred_brand_name", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(choices=[("submitted", "Submitted"), ("under_review", "Under review"), ("allocated", "Allocated"), ("delivered", "Delivered"), ("cancelled", "Cancelled"), ("rejected", "Rejected")], default="submitted", max_length=20)),
                ("priority", models.CharField(editable=False, max_length=2)),
                ("due_date", models.DateField(editable=False)),
                ("entitlement_month", models.DateField(default=current_month_start, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applicant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lpg_applications", to=settings.AUTH_USER_MODEL)),
                ("household", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="applicants.household")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="lpgapplication",
            constraint=models.UniqueConstraint(fields=("household", "entitlement_month"), name="one_lpg_application_per_household_month"),
        ),
    ]
