# Generated by Django 6.1.1 on 2026-09-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_remove_preferred_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional private coordinate used for dealer-distance ranking.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional private coordinate used for dealer-distance ranking.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
