# Generated by Django 6.1.1 on 2026-09-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0004_household_latitude_household_longitude"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="location_match_confidence",
            field=models.CharField(
                choices=[
                    ("unresolved", "Not resolved"),
                    ("user_entered", "User entered"),
                    ("canonical", "Canonical reference"),
                    ("fuzzy", "Fuzzy match"),
                ],
                default="unresolved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="location_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional canonical municipality, ward, or tole reference.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="households",
                to="locations.locationunit",
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="house_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="household",
            name="municipality",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="household",
            name="tole",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Tole / street"
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="ward",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
