# Generated by Django 6.1.1 on 2026-09-13 02:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("dealers", "0005_remove_legacy_single_brand_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CylinderUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "manufacturer_serial_number",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "capacity_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cylinder_units",
                        to="brands.lpgbrand",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cylinder_units",
                        to="dealers.dealerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_code"],
            },
        ),
        migrations.CreateModel(
            name="CylinderFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fill_reference",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("filled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In dealer stock"),
                            ("reserved", "Reserved"),
                            ("sold_pending_receipt", "Sold, receipt pending"),
                            ("receipt_confirmed", "Receipt confirmed"),
                            ("returned_empty", "Returned empty"),
                            ("damaged", "Damaged"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_stock",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cylinder_fills",
                        to="brands.lpgbrand",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cylinder_fills",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_cylinder_fills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cylinder_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fills",
                        to="inventory.cylinderunit",
                    ),
                ),
            ],
            options={
                "ordering": ["filled_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cylinder_unit", "filled_at"),
                        name="one_fill_event_per_cylinder_timestamp",
                    )
                ],
            },
        ),
    ]
