# Generated by Django 6.1.1 on 2026-09-12

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dealer_name", models.CharField(max_length=160)),
                ("proprietor_name", models.CharField(max_length=160)),
                ("mobile_number", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("municipality", models.CharField(max_length=120)),
                ("ward", models.CharField(max_length=20)),
                ("tole", models.CharField(max_length=160, verbose_name="Tole / street")),
                ("address", models.CharField(max_length=240)),
                ("house_plot_number", models.CharField(max_length=60, verbose_name="House / plot number")),
                ("lpg_brand", models.CharField(max_length=120, verbose_name="LPG brand")),
                ("authorization_license", models.CharField(max_length=120, verbose_name="Authorization / license number")),
                ("gps_latitude", models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ("gps_longitude", models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ("shop_photo", models.FileField(upload_to="dealers/shop-photos/")),
                ("supporting_document", models.FileField(blank=True, upload_to="dealers/supporting-documents/")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("pending_verification", "Pending Company Verification"), ("correction_required", "Verification Correction Required"), ("physically_verified", "Physically Verified"), ("pending_approval", "Pending Company Approval"), ("active", "Company Approved / Active"), ("rejected", "Rejected"), ("suspended", "Suspended"), ("inactive", "Inactive")], default="submitted", max_length=30)),
                ("verification_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dealer_approvals", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="dealer_profile", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dealer_verifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_verify_dealers", "Can perform physical dealer verification"),
                    ("can_approve_dealers", "Can approve or reject dealers"),
                ],
            },
        ),
    ]
