# Generated by Django 6.1.1 on 2026-09-13 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0005_remove_legacy_single_brand_fields"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerprofile",
            name="address",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="house_plot_number",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="House / plot number"
            ),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="municipality",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="tole",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Tole / street"
            ),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="ward",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="DealerCoverageArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_level",
                    models.CharField(
                        choices=[("tole", "Tole"), ("ward", "Ward")], max_length=10
                    ),
                ),
                ("municipality", models.CharField(blank=True, max_length=120)),
                ("ward", models.CharField(blank=True, max_length=20)),
                ("tole", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_dealer_coverage_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_areas",
                        to="dealers.dealerprofile",
                    ),
                ),
                (
                    "location_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_coverage_areas",
                        to="locations.locationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["municipality", "ward", "tole", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "dealer",
                            "coverage_level",
                            "municipality",
                            "ward",
                            "tole",
                        ),
                        name="one_dealer_coverage_area",
                    )
                ],
            },
        ),
    ]
