# Generated by Django 6.1.1 on 2026-09-13 02:29

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("municipality", "Municipality"),
                            ("ward", "Ward"),
                            ("tole", "Tole"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name_en", models.CharField(max_length=160)),
                ("name_ne", models.CharField(blank=True, max_length=160)),
                ("normalized_name", models.CharField(db_index=True, max_length=160)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("district_name", models.CharField(blank=True, max_length=80)),
                ("is_kathmandu_valley", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.locationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name_en", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "normalized_name", "level"),
                        name="one_location_name_per_parent_level",
                    )
                ],
            },
        ),
    ]
