# Generated by Django 6.1.1 on 2026-09-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationunit",
            name="is_kathmandu_valley",
            field=models.BooleanField(default=False),
        ),
    ]
