# Generated by Django 6.1.1 on 2026-09-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_locationunit_is_kathmandu_valley"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=160)),
                ("normalized_alias", models.CharField(db_index=True, max_length=160)),
                (
                    "source",
                    models.CharField(
                        default="NOC / dealer stewardship", max_length=120
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alias_records",
                        to="locations.locationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["normalized_alias", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "normalized_alias"),
                        name="one_alias_per_location",
                    )
                ],
            },
        ),
    ]
