# Generated by Django 6.1.1 on 2026-09-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="cylinder_fill",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation",
                to="inventory.cylinderfill",
            ),
        ),
        migrations.AddField(
            model_name="allocationrun",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
