# Generated by Django 6.1.1 on 2026-09-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocations", "0002_allocation_cylinder_fill_allocationrun_stock_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="location_match_level",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="allocation",
            name="location_match_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
    ]
